os: osx
osx_image: xcode11
language: swift
#script: xcodebuild clean build test -project
#CIExample/CIExample.xcodeproj -scheme CIExample -sdk iphonesimulator -destination "platform=iOS Simulator,OS=12.1,name=iPhone 8" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
script:
- xcodebuild CIExample -project CIExample.xcodeproj -scheme CIExample -destination "platform=iOS Simulator,name=iPhone 8" -sdk iphonesimulator13.0 CODE_SIGNING_REQUIRED=NO
